name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
        run: docker-compose -f "docker-compose.ci.yml" up -d --build
    - name: Install webpacker
      run: bundle exec rails webpacker:install
    - name: Stop containers
      if: always()
      run: docker-compose --file docker-compose.ci.yml down
