name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
        run: docker-compose --file docker-compose.ci.yml run ci
      - name: ls ./app/
        run: ls ${{ github.workspace }}/app/
      - name: ls app root
        run: ls ${{ github.workspace }}
      - name: ls ./../
        run: ls ./../
      - name: ls ./../../
        run: ls ./../../
      - name: ls /
        run: ls /
      - name: Pwd
        run: pwd
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
